import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Generates a professional PDF invoice for a customer.
 */
export const generateInvoicePDF = (invoiceData: any) => {
    // Create new PDF document
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // 1. Header & Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(33, 33, 33);
    doc.text('INVOICE', pageWidth / 2, 20, { align: 'center' });
    
    // 2. Business Details (Static placeholder for now, ideally passed in)
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("KHATA DIGITAL LEDGER", 20, 35);
    doc.text("Pakistan Business Management System", 20, 40);
    
    // 3. Invoice Metadata
    doc.setFont("helvetica", "bold");
    doc.text(`Invoice #: ${invoiceData.invoiceNumber}`, pageWidth - 20, 35, { align: 'right' });
    doc.setFont("helvetica", "normal");
    doc.text(`Date: ${new Date(invoiceData.createdAt).toLocaleDateString()}`, pageWidth - 20, 40, { align: 'right' });
    if (invoiceData.dueDate) {
        doc.text(`Due Date: ${new Date(invoiceData.dueDate).toLocaleDateString()}`, pageWidth - 20, 45, { align: 'right' });
    }
    
    // 4. Customer Details
    doc.setFont("helvetica", "bold");
    doc.text('Bill To:', 20, 60);
    doc.setFont("helvetica", "normal");
    doc.text(invoiceData.customer.name, 20, 65);
    doc.text(`Phone: ${invoiceData.customer.phone}`, 20, 70);
    if (invoiceData.customer.address) {
        doc.text(invoiceData.customer.address, 20, 75);
    }
    
    // 5. Items Table
    const tableData = invoiceData.transaction.items.map((item: any) => [
        item.description,
        Number(item.quantity).toFixed(0),
        `PKR ${Number(item.unitPrice).toLocaleString()}`,
        `PKR ${Number(item.totalPrice).toLocaleString()}`
    ]);
    
    (doc as any).autoTable({
        startY: 85,
        head: [['Description', 'Qty', 'Unit Price', 'Total']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185], textColor: 255 },
        styles: { fontSize: 9, cellPadding: 3 },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 20, halign: 'center' },
            2: { cellWidth: 35, halign: 'right' },
            3: { cellWidth: 35, halign: 'right' }
        }
    });
    
    // 6. Summary Totals
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    
    doc.setFont("helvetica", "bold");
    doc.text("Summary", pageWidth - 80, finalY);
    
    doc.setFont("helvetica", "normal");
    doc.text("Subtotal:", pageWidth - 80, finalY + 7);
    doc.text(`PKR ${Number(invoiceData.totalAmount).toLocaleString()}`, pageWidth - 20, finalY + 7, { align: 'right' });
    
    if (Number(invoiceData.taxAmount) > 0) {
        doc.text("Tax Amount:", pageWidth - 80, finalY + 12);
        doc.text(`PKR ${Number(invoiceData.taxAmount).toLocaleString()}`, pageWidth - 20, finalY + 12, { align: 'right' });
    }
    
    doc.line(pageWidth - 80, finalY + 15, pageWidth - 20, finalY + 15);
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Total Amount:", pageWidth - 80, finalY + 22);
    doc.text(`PKR ${Number(invoiceData.totalAmount).toLocaleString()}`, pageWidth - 20, finalY + 22, { align: 'right' });
    
    // 7. Footer
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150);
    doc.text("Thank you for your business!", pageWidth / 2, 280, { align: 'center' });
    doc.text("Generated by Khata Digital Ledger", pageWidth / 2, 285, { align: 'center' });
    
    // 8. Save/Download
    doc.save(`Invoice_${invoiceData.invoiceNumber}.pdf`);
};
